"""empty message

Revision ID: 743ae393c5ca
Revises: 6d53a665a35d
Create Date: 2020-10-30 15:08:03.126600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743ae393c5ca'
down_revision = '6d53a665a35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('writer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'writer', ['writer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'writer_id')
    # ### end Alembic commands ###
