"""empty message

Revision ID: a7a335f37d3d
Revises: 30682f5d97e9
Create Date: 2020-10-30 14:43:34.025800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a335f37d3d'
down_revision = '30682f5d97e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('writer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'writer', ['writer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'writer_id')
    op.drop_table('writer')
    # ### end Alembic commands ###
