"""empty message

Revision ID: adf637d8f4c2
Revises: bc327ce7b39c
Create Date: 2020-10-30 15:15:11.657852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf637d8f4c2'
down_revision = 'bc327ce7b39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('writer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'writer', ['writer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'writer_id')
    # ### end Alembic commands ###
