"""empty message

Revision ID: bc327ce7b39c
Revises: 743ae393c5ca
Create Date: 2020-10-30 15:12:48.482341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc327ce7b39c'
down_revision = '743ae393c5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_writer_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'writer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('writer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_writer_id_fkey', 'posts', 'writer', ['writer_id'], ['id'])
    # ### end Alembic commands ###
